// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }




// "use client"

// import { useEffect, useState } from "react"
// import { useAuth } from "@/app/(provider)/authProvider"

// export default function AdminLayout({children}){

//   const { user } = useAuth;
//   return (
//     <div className="p-8">
//      <h1 className=" text-xl font-bold ">Admin</h1>
//      <p>admin/page.js Нэвтэрсэн: {user ? user.email: "Зочин"} </p>
//     </div>
//   )


// }

import { AuthProvider } from "./(provider)/authProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}